# (c) Axel Naumann, 2017-03-07, axel@cern.ch
# See file LICENSE in the top-most directory for the license.

plugins:
  jira_enabled:
    default: true
    client: true
  jira_project_urls:
    default: ''
    refresh: true
    type: list
    client: true
